apiVersion: v1alpha1
kind: Role
metadata:
  name: comment-next-public-apis
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "评论组件 Next"
    rbac.authorization.halo.run/display-name: "评论组件 Next 公开接口"
rules:
  - apiGroups: [ "api.commentnext.xhhao.com" ]
    resources: [ "captcha/generate" ]
    verbs: [ "get" ]
  - apiGroups: [ "api.commentnext.xhhao.com" ]
    resources: [ "config" ]
    verbs: [ "list" ]
